FROM python:3.11-slim-buster
RUN apt-get update && \
    apt-get update

ARG WORKDIR=/usr/src/tinymod
RUN mkdir -p ${WORKDIR}
WORKDIR ${WORKDIR}

RUN python -m pip install --upgrade pip
COPY . .
RUN python -m pip install -e .

CMD ["python", "tinymod"]